About page michael
codesydney/aicta pull request #11
Opened 2023-03-31 10:20 UTC by kaka5277

<img width="495" alt="image" src="https://user-images.githubusercontent.com/101174325/229094016-00bbfc28-a9b6-4a3d-99a7-5dc5ad951f47.png"><img width="679" alt="image" src="https://user-images.githubusercontent.com/101174325/229094190-f6af8f14-15a4-4ba1-875c-7016c7c6f6f5.png">

2023-04-01 02:49 UTC, davidtaing commented on about.html
> +                                            <a href="#" class="fw-bold color-000"> pleno@bigpond.com </a>
This link isn't working. Try out `mailto:<email-address>`.

Source: https://css-tricks.com/snippets/html/mailto-links/

2023-04-01 02:49 UTC, davidtaing commented on about.html
> +                        <p>More than 1000 companies trust and choose AICTA</p>
This is a brand new company, so we won't be able to claim that 1000 companies trust us. I feel that it's better to remove this line for now.

Also look into the career form section above (lines 255 to 313) and look at modifying/removing that section. _I'm not able to highlight them, but I've left a screenshot below._

![image](https://user-images.githubusercontent.com/8443215/229262099-5b00886e-9a59-45ea-be9a-7170be92eb6a.png)

2023-04-01 02:49 UTC, davidtaing commented on about.html
> +                            (+61)0417 90 6971
Can you please format this as follows?

![image](https://user-images.githubusercontent.com/8443215/229262194-127ccd5c-c9f4-43d7-a48c-b41821d2889c.png)

Source: https://www.stylemanual.gov.au/grammar-punctuation-and-conventions/numbers-and-measurements/telephone-numbers#use_chunks_of_digits_to_help_people_read_telephone_numbers

2023-04-01 02:49 UTC, davidtaing commented on about.html
> +                            pleno@bigpond.com
Looks like we need to make this clickable. Can you please wrap this email address inside an `<a>` tag with a `href="mailto:<email-address>"` property?

2023-04-01 02:49 UTC, davidtaing commented
Hold off on making changes for a sec. I'll fix up the merge conflict for you here first and will make some changes to this branch.

2023-04-01 03:08 UTC, davidtaing requested changes
Thanks for your PR @kaka5277.

- I've left some comments above, please review these when you get a chance.
- **[Important]** I've also merged `main` into this branch and fixed up the merge conflict. This means that I've made changes to your branch, and you will have to sync up with my changes.

  In order synchronize my changes with yours, please run `$ git pull` in your terminal.


- Finally, I noticed that the branch wasn't synchronized with main before new changes were added. This can cause problems such as the merge conflict from before. Fortunately, there haven't been too many changes, so the merge conflict was not bad.

  Linking to my comment to @ZizhangOu since its relevant: 
https://github.com/codesydney/aicta/pull/9#issuecomment-1474730658

  I'll try to create some diagrams to make this easier to understand. Those will be added in future comments

2023-04-01 03:35 UTC, davidtaing commented
When we merge two branches, git will create a merge commit. So after `about-page-michael` was merged into `main`, there was a new merge commit added to main.

Let's say we made two commits `B` & `C` to the `about-page`. The merge added a merge commit of `D`. So we can say the history of the `about-page` file in `main` is:

`B` -> `C` -> `D`.

When additional changes were added to the `about-page` file in the `about-page-michael` branch, we did not have `D` in our history. So in this branch we had a history of:

`B` -> `C` -> `E`.

This is why there was a merge conflict.

Fortunately, not much has changed, so it was not bad. But imagine if you had 300+ lines of code on one branch and another 300+ lines of code in the other. That can be extremely difficult to fix.

### Without creating a new branch/synchronizing with main.
![untitled(20)](https://user-images.githubusercontent.com/8443215/229263302-1f8f0e5e-0560-4a2f-88b5-0c6d4d9ff857.png)

---

Creating a new branch is almost always the best way to go. If you would like to reuse the branch's name, I'll suggest deleting the branch after you merge and creating a new one with the same name.

Not only do you capture your merge commit, but it also capture any changes that other developers have made to main.

### With new branch or synchronizing with main.
![untitled(21)](https://user-images.githubusercontent.com/8443215/229263301-a2e91c54-e82e-47ac-8ad1-c8bd36c088f6.png)

If you want to go in depth, here's a good 1 hour 40 mins talk on Git:
https://www.youtube.com/watch?v=1ffBJ4sVUb4

---

Pinging you guys to loop you in. @kaka5277 @ZizhangOu 

Feel free to ask any follow-up questions. 

Even for those not directly involved in this thread, you're more then welcome to ask. e.g. Code.Sydney member, or general GitHub user. :wink:

2023-04-01 03:40 UTC, kaka5277 commented
Hi Dave,
&nbsp;Thank you so much for not only reviewing for me ,but also providing so detailed documents about Git skills.really appreciate your time and help.I'll have a look and learn it.
Michael




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "codesydney/aicta"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 中午11:35
***@***.***&gt;;
抄送:&nbsp;"Jun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [codesydney/aicta] About page michael (PR #11)





 
When we merge two branches, git will create a merge commit. So after about-page-michael was merged into main, there was a new merge commit added to main.
 
Let's say we made two commits B &amp; C to the about-page. The merge added a merge commit of D. So we can say the history of the about-page file in main is:
 
B -&gt; C -&gt; D.
 
When additional changes were added to the about-page file in the about-page-michael branch, we did not have D in our history. So in this branch we had a history of:
 
B -&gt; C -&gt; E.
 
This is why there was a merge conflict.
 
Fortunately, not much has changed, so it was not bad. But imagine if you had 300+ lines of code on one branch and another 300+ lines of code in the other. That can be extremely difficult to fix.
 
Without creating a new branch/synchronizing with main.
 

 
 
Creating a new branch is almost always the best way to go. If you would like to reuse the branch's name, I'll suggest deleting the branch after you merge and creating a new one with the same name.
 
Not only do you capture your merge commit, but it also capture any changes that other developers have made to main.
 
With new branch or synchronizing with main.
 

 
If you want to go in depth, here's a good 1 hour 40 mins talk on Git:
 https://www.youtube.com/watch?v=1ffBJ4sVUb4
 
 
Pinging you guys to loop you in. @kaka5277 @ZizhangOu
 
Feel free to ask any follow-up questions.
 
Even for those not directly involved in this thread, you're more then welcome to ask. e.g. Code.Sydney member, or general GitHub user. 😉
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2023-04-02 01:44 UTC, davidtaing commented on about.html
> +                        <p>More than 1000 companies trust and choose AICTA</p>
Thanks for doing that Michael. Just need to go to Line 321 as well. Can you remove the subheadline here since it says 1000 companies trust AICTA?

2023-04-03 04:16 UTC, davidtaing commented
@kaka5277, please let me know when this is ready for another review. Thanks

2023-04-03 12:14 UTC, kaka5277 commented
hi dave,it is already for review.

2023-04-03 12:55 UTC, davidtaing approved these changes
Looks good, great work.

Love that you broke up the changes into multiple commits.

Approved @kaka5277.

2023-04-03 12:55 UTC, merged

2023-04-03 13:01 UTC, kaka5277 commented
thank you so much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "codesydney/aicta"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月3日(星期一) 晚上8:55
***@***.***&gt;;
抄送:&nbsp;"Jun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [codesydney/aicta] About page michael (PR #11)





 
Merged #11 into main.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;